version: "3"

services:
  api:
    container_name: api
    build:
        context: .
        dockerfile: async_api/Dockerfile
    ports:
      - "8000"
    volumes:
      - ./async_api:/data/async_api
    env_file:
      - ./async_api/.env
      - ./elasticsearch/.env
      - ./.env
    depends_on:
      - elasticsearch
      - redis
    networks:
      - int_net

  auth_api:
    container_name: auth_api
    build:
      context: .
      dockerfile: auth_api/Dockerfile
    ports:
      - "5000"
    env_file:
      - ./auth_api/.env.docker-compose
      - ./.env
    depends_on:
      - auth_postgres
      - redis
    networks:
      - int_net

  admin_panel:
    container_name: admin_panel
    build:
      context: .
      dockerfile: admin/Dockerfile
    ports:
      - "80"
    env_file:
      - ./admin/.env.docker-compose
      - ./.env
    depends_on:
      - data_postgres
      - redis
    networks:
      - int_net

  data_postgres:
    image: postgres:13
    container_name: data_postgres
    ports:
      - "5432"
    volumes:
      - ${HOME}/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - int_net

  auth_postgres:
    image: postgres:13
    container_name: auth_postgres
    ports:
      - "5432"
    volumes:
      - ${HOME}/postgresql/auth_data:/var/lib/postgresql/data
    env_file:
      - ./auth_postgres/.env
    networks:
      - int_net

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    ports:
      - "9200"
      - "9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    env_file:
      - ./elasticsearch/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - int_net

  redis:
    image: redis:7.0.0
    container_name: redis
    entrypoint: redis-server
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379"
    volumes:
      - $HOME/redis/data:/data
    networks:
      - int_net

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - api
    links:
      - api
    networks:
      - ext_net
      - int_net

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    depends_on:
      - auth_api
    networks:
      - ext_net
      - int_net

volumes:
  esdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/elasticsearch/data

networks:
  ext_net:
  int_net:
    internal: true
